name: Release
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/SSH_PRIVATE_KEY"
      - run: chmod 0600 "$HOME/.ssh/SSH_PRIVATE_KEY"
      - name: Rsync deploy
        run: rsync --exclude-from=rsync_exclude.txt --del -e "ssh -p ${{ secrets.SERVER_PORT }} -i $HOME/.ssh/SSH_PRIVATE_KEY -o StrictHostKeyChecking=no" --archive --compress --delete . ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_DEPLOY_PATH }}
      - name: docker-compose
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: "cd ${{ secrets.SERVER_DEPLOY_PATH }}
          && sudo docker-compose up -d --build
          && sudo chmod 755 -R storage && sudo chmod 755 -R bootstrap/cache
          && docker exec app composer install
          && docker exec app php artisan migrate"
